name: cd/cd

on:
  push:
    branches: ['main', 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: ['main', 'release/**', 'task/**', 'feature/**', 'epic/**']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Examples
      run: make
